version: '3.8'
services:
  config-server:
    image: config-server:latest
    build: ./config-server
    ports:
      - "8888:8888"
  
  eureka-server:
    image: eureka-server:latest
    build: ./eureka-server
    ports:
      - "8761:8761"

  api-gateway:
    image: api-gateway:latest
    build: ./api-gateway
    ports:
      - "8080:8080"

  ms-cursos:
    image: ms-cursos:latest
    build: ./ms-cursos
    ports:
      - "8081:8081"
    depends_on:
      - mysql 
  
  ms-estudiantes:
    image: ms-estudiantes:latest
    build: ./ms-estudiantes
    ports:
      - "8082:8082"
    depends_on:
      - mysql  

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456 
      MYSQL_DATABASE: curso_db  
      MYSQL_DATABASE: estudiante_db  
    ports:
      - "3306:3306"
