server:
  port: 8082

spring:
  application:
    name: estudiante-service
  datasource:
    url: jdbc:mysql://localhost:3306/estudiante_db  
    username: root 
    password: 123456  

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
