server:
  port: 8081

spring:
  application:
    name: curso-service
  datasource:
    url: jdbc:mysql://localhost:3306/curso_db  
    username: root 
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
